spring:
  application:
    name: security-ground-up

  # Datasource settings
  datasource:
    url: jdbc:postgresql://localhost:5432/security_playground
    username: root
    password: adminadmin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: bhm-pool

  flyway:
    enabled: true
    locations: classpath:schema
    validate-on-migrate: true
    mixed: true
    out-of-order: true
    table: schema_version

server:
  port: 9090
  servlet:
    context-path: /api